# Generated by Django 4.1.4 on 2022-12-26 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_alter_canteen_canteen_state_alter_dish_dish_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canteen',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='store',
            name='manager',
        ),
        migrations.AddField(
            model_name='manager',
            name='manager_canteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='canteen.canteen', verbose_name='管理的食堂'),
        ),
        migrations.AddField(
            model_name='manager',
            name='manager_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='canteen.store', verbose_name='管理的商铺'),
        ),
    ]
