# Generated by Django 4.1.4 on 2022-12-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_remove_canteen_manager_remove_store_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canteen',
            options={'ordering': ['canteen_id'], 'verbose_name': '食堂信息', 'verbose_name_plural': '食堂信息'},
        ),
    ]
