# Generated by Django 4.1.4 on 2022-12-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0004_alter_canteen_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='canteen_state',
            field=models.CharField(choices=[('营业中', '营业中'), ('休息中', '休息中')], max_length=20, verbose_name='食堂状态'),
        ),
    ]
