# Generated by Django 4.1.4 on 2022-12-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0005_alter_canteen_canteen_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='canteen',
            new_name='canteen_id',
        ),
    ]
