# Generated by Django 4.1.4 on 2022-12-26 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0007_rename_store_decribe_store_store_describe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dish_decribe',
            new_name='dish_describe',
        ),
    ]
