# Generated by Django 4.1.4 on 2022-12-27 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0008_rename_dish_decribe_dish_dish_describe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='dishes',
        ),
        migrations.AddField(
            model_name='dish',
            name='Store_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='商铺编号', to='canteen.store'),
            preserve_default=False,
        ),
    ]
