# Generated by Django 4.1.4 on 2022-12-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0009_remove_store_dishes_dish_store_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='Store_id',
            new_name='store_id',
        ),
    ]
