# Generated by Django 4.1.4 on 2022-12-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0010_rename_store_id_dish_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_order_num',
            field=models.IntegerField(default=0, verbose_name='下单数量'),
        ),
    ]
