# Generated by Django 4.1.4 on 2022-12-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0011_dish_dish_order_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dish_order_num',
        ),
    ]
