# Generated by Django 4.1.4 on 2022-12-30 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0014_alter_dish_dish_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
