# Generated by Django 4.1.4 on 2022-12-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False, verbose_name='地址编号')),
                ('building', models.CharField(max_length=20, verbose_name='楼栋编号')),
                ('floor', models.CharField(max_length=10, verbose_name='楼层编号')),
                ('dormitory_num', models.CharField(max_length=10, verbose_name='门牌号')),
                ('address_describe', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址描述')),
            ],
            options={
                'verbose_name': '地址信息',
                'verbose_name_plural': '地址信息',
                'db_table': 'address',
                'ordering': ['address_id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='顾客编号')),
                ('customer_name', models.CharField(max_length=20, verbose_name='顾客昵称')),
                ('customer_sex', models.IntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='顾客联系方式')),
                ('customer_pwd', models.CharField(max_length=100, verbose_name='顾客密码')),
                ('addresses', models.ManyToManyField(db_table='customer_address', to='user.address')),
            ],
            options={
                'verbose_name': '顾客信息',
                'verbose_name_plural': '顾客信息',
                'db_table': 'customer_info',
                'ordering': ['customer_id'],
            },
        ),
    ]
