# Generated by Django 4.1.4 on 2022-12-30 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0015_delete_manager'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False, verbose_name='管理员编号')),
                ('manager_name', models.CharField(max_length=20, unique=True, verbose_name='管理员昵称')),
                ('manager_phone', models.CharField(max_length=20, verbose_name='管理员联系方式')),
                ('manager_pwd', models.CharField(max_length=100, verbose_name='管理员密码')),
                ('manager_label', models.IntegerField(choices=[(0, '商家'), (1, '食堂管理员')], verbose_name='管理员类型')),
                ('manager_canteen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='canteen.canteen', verbose_name='管理的食堂')),
                ('manager_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='canteen.store', verbose_name='管理的商铺')),
            ],
            options={
                'verbose_name': '管理员信息',
                'verbose_name_plural': '管理员信息',
                'db_table': 'manager',
                'ordering': ['manager_id'],
            },
        ),
    ]
