# Generated by Django 4.1.4 on 2022-12-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customer_phone',
            field=models.CharField(default=18475334567, max_length=20, verbose_name='顾客联系方式'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(max_length=10, verbose_name='楼栋编号'),
        ),
    ]
