# Generated by Django 4.1.4 on 2022-12-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_address_customer_phone_alter_address_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='customer_phone',
            new_name='phone',
        ),
    ]
