# Generated by Django 4.1.4 on 2022-12-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indent',
            name='indent_state',
            field=models.IntegerField(choices=[(0, '未下单'), (1, '已下单'), (2, '已发货'), (3, '已送达'), (4, '已评价')], default=0, verbose_name='订单状态'),
        ),
    ]
