# Generated by Django 4.1.4 on 2022-12-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_indent_indent_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indent',
            name='indent_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='订单价格'),
        ),
    ]
