# Generated by Django 4.1.4 on 2022-12-28 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('order', '0004_alter_indent_indent_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='indent',
            name='indent_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address', verbose_name='订单地址'),
        ),
    ]
