# Generated by Django 4.1.4 on 2022-12-28 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0012_remove_dish_dish_order_num'),
        ('order', '0006_alter_indentinventory_dish_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indentinventory',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.dish'),
        ),
    ]
