# Generated by Django 4.1.4 on 2022-12-29 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0012_remove_dish_dish_order_num'),
        ('order', '0007_alter_indentinventory_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indent',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='canteen.store', verbose_name='商铺'),
        ),
    ]
