# Generated by Django 4.1.4 on 2022-12-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_indent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='评价时间'),
        ),
    ]
